[window]
opacity = 0.5
padding.x = 8
padding.y = 4

decorations = "Full"
decorations_theme_variant = "Dark" # "Light"

[font]
normal.family = "JetBrainsMono Nerd Font"

# bold.family = "Cascadia Code PL"
# italic.family = "Cascadia Code PL"
# bold_italic.family = "Cascadia Code PL"
